name: Container build from Alpine 

on:
  push:
    branches:
      - master
    paths:
      - "alpine/Dockerfile"
  pull_request:
    branches:
      - master
    paths:
      - "alpine/Dockerfile"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build the Alpine based container image
      run: docker build . --file ./alpine/Dockerfile --tag firefox:$(date +%s)-alpine
