name: Buildah Build Alpine based

on:
  push:
    branches:
      - master
      - develop
    paths:
      - "alpine/Dockerfile"
  pull_request:
    branches:
      - master
    paths:
      - "alpine/Dockerfile"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    # https://github.com/redhat-actions/buildah-build
    - name: Buildah build
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: firefox
        tags: ${{ github.ref_name }}-alpine
        containerfiles: |
          ./alpine/Containerfile
